language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

env: AUTHOR_TESTING=1
before_install:
  - cpanm JSON::PP
  - cpanm Perl6::Slurp
  - cpanm Test::MinimumVersion
  - cpanm Test::Pod
  - cpanm Test::Strict
  - cpanm Test::Synopsis
# This is currently erroring out on Travis.
#  - cpanm Perl::Critic

branches:
  only:
    - master
